---
# Applies Automatically To Any Host Labeled env=prod In GCP (See
# inventory/gcp.yaml's keyed_groups).

environment_name: prod
vault_jwt_auth_backend_path: "jwt-nomad-prod"

bootstrap_expect: 3

# Nomad/Consul Server discovery configs are passed in at runtime via startup scripts
retry_join: ""

traefik_active_instances:
  - prod-public