# Postgres Admin-Tier Credentials — Generated By Terraform, Never Typed
# By Hand, Written To ONE Shared KV Path.
#
# Two passwords, two different jobs:
#   - postgres_superuser: POSTGRES_USER/POSTGRES_PASSWORD for the
#     container's own bootstrap. Used exactly once, in the init script,
#     to create vault-admin + both databases. Dormant after that —
#     nothing else in this system ever authenticates as this role.
#   - vault_admin_db: the role Vault itself authenticates as, for both
#     Postgres connections (metrics + monitoring, dev + prod). Created
#     BY the superuser during init, granted CREATEROLE + ownership of
#     both databases — never superuser itself. This is what would get
#     rotated later via Vault's own `rotate-root` mechanism, once
#     confirmed, without ever touching the container's bootstrap
#     credential.
#
# Shared across dev+prod deliberately, same reasoning as Redis/AI-agent
# secrets that are per-value, not per-env — there is exactly ONE
# vault-admin password used across both environments' Postgres
# instances (each is a totally separate database on a totally separate
# cluster, so reusing the same password isn't actually reusing the same
# credential's blast radius the way it would in a single shared system).

resource "random_password" "postgres_superuser" {
  length  = 32
  special = false
}

resource "random_password" "vault_admin_db" {
  length  = 32
  special = false
}

# Written to Vault KV, readable ONLY by the Postgres Nomad job's own
# Workload Identity role (needs both values for its init script's
# template stanza — the superuser password to launch the container,
# vault_admin_db's password to actually create that role in SQL).
# Vault's own engines.tf connections reference random_password.vault_admin_db.result
# directly (same module/state) rather than reading this KV entry back —
# no round-trip needed for Vault's own use of the value.
resource "vault_kv_secret_v2" "postgres_admin" {
  mount = vault_mount.kv.path
  name  = "shared/postgres/admin"
  data_json = jsonencode({
    superuser_password = random_password.postgres_superuser.result
    vault_admin_password = random_password.vault_admin_db.result
  })
}
