# Redis Password — Generated By Terraform, Never Typed By Hand
resource "random_password" "redis" {
  for_each = toset(["dev", "prod"])
  length   = 32
  special  = false
}

resource "vault_kv_secret_v2" "cartservice_redis" {
  for_each = toset(["dev", "prod"])
  mount    = vault_mount.kv.path
  name     = "${each.key}/cartservice/redis"
  data_json = jsonencode({
    password = random_password.redis[each.key].result
  })
}

# nomad-sentinel's config (Gemini API key, Slack webhook) is seeded
# directly into Vault, once, by hand — not mirrored from GCP Secret
# Manager. Storing the same value in two secret stores adds cost and a
# second place either value can drift or leak, with no corresponding
# benefit here since nothing else ever needs to read them from GCP
# after Vault has them.
#
# Run once, per environment, after this module has been applied:
#   vault kv put kv/dev/nomad-sentinel/config gemini_api_key=<value> slack_webhook_url=<value>
#   vault kv put kv/prod/nomad-sentinel/config gemini_api_key=<value> slack_webhook_url=<value>
#
# nomad-sentinel authenticates to Nomad's own API using its own
# Workload Identity, not a value stored here — see modules/nomad/acl.tf.
