# Redis Password — Generated By Terraform, Never Manually Set
resource "random_password" "redis" {
  for_each = toset(["dev", "prod"])
  length   = 32
  special  = false
}

resource "vault_kv_secret_v2" "cartservice_redis" {
  for_each = toset(["dev", "prod"])
  mount    = vault_mount.kv.path
  name     = "${each.key}/cartservice/redis"
  data_json = jsonencode({
    password = random_password.redis[each.key].result
  })
}

# AI Agent Config — Gemini API Key + Slack Webhook (Flag 3: Shared Across
# Both Envs, Not Per-Environment) + Nomad Token (Handed Off From The
# nomad/ Root Module Via Secret Manager — See README For Why These Are
# Separate State Files And Can't Reference Each Other's Resources
# Directly)
data "google_secret_manager_secret_version" "gemini_api_key" {
  secret = "gemini-api-key" # manually seeded operator-tier secret, one value for both envs
}

data "google_secret_manager_secret_version" "slack_webhook_url" {
  secret = "slack-webhook-url" # manually seeded operator-tier secret, one value for both envs
}

# NOTE: no nomad_token field here. nomad-sentinel is itself a Nomad
# task — it should authenticate to Nomad's own API using its own
# Workload Identity (job-spec `identity {}` block), same no-standing-
# credential pattern as its Vault access, rather than a static ACL
# token relayed through Vault. This removes the only cross-module
# dependency vault/ previously had on nomad/'s output — vault/ can now
# be applied with zero dependency on dev/ or prod/ having ever run.
#
# Whether Nomad's own API actually supports task-side Workload Identity
# auth the same confirmed way Vault/Consul do hasn't been independently
# verified this session — worth confirming before nomad-jobs/ is
# written. nomad/'s module still mints a nomad-sentinel ACL token as a
# fallback/interim option (see modules/nomad/acl.tf) in case it doesn't.

resource "vault_kv_secret_v2" "ai_agent_config" {
  for_each = toset(["dev", "prod"])
  mount    = vault_mount.kv.path
  name     = "${each.key}/ai-agent/config"
  data_json = jsonencode({
    gemini_api_key    = data.google_secret_manager_secret_version.gemini_api_key.secret_data
    slack_webhook_url = data.google_secret_manager_secret_version.slack_webhook_url.secret_data
  })
}
