---
- name: Configure Nomad Client Nodes
  hosts: "{{ target_hosts | default('role_worker') }}" #target_hosts is overrident by packer during image build 
  become: true
  vars:
    consul_mode: client
    nomad_mode: client
    docker_extra_group_users: ["nomad"]
    common_install_gcloud_cli: true
  roles:
    - common
    - consul
    - nomad
    - docker
    - falco
