---
- name: Configure Nomad Server Nodes
  hosts:  "{{ target_hosts | default('role_control_plane') }}" #target_hosts is overrident by packer during image build 
  become: true
  vars:
    consul_mode: server
    nomad_mode: server
    common_install_gcloud_cli: true
  roles:
    - common
    - consul
    - nomad
