---
falco_apt_key_url: "https://falco.org/repo/falcosecurity-packages.asc"

falco_engine_kind: "modern_ebpf"
falco_config_dir: /etc/falco

falco_webhook_url: "__FALCO_WEBHOOK_URL_PLACEHOLDER__"
falco_alert_severity_threshold: "warning"
