---
falco_apt_key_url: "https://falco.org/repo/falcosecurity-3672BA8F.asc"
falco_gpg_key_ring: "/usr/share/keyrings/falco-archive-keyring.gpg"
falco_apt_repo: "deb [signed-by={{ falco_gpg_key_ring }}] https://download.falco.org/packages/deb stable main"

falco_engine_kind: "modern_ebpf"
falco_config_dir: /etc/falco

falco_webhook_url: "http://falco-webhook.service.consul:8080/"
falco_alert_severity_threshold: "warning"
